USE [master]
GO

/****** Object:  Database [LibrosWeb]    Script Date: 19/09/2022 19:26:19 ******/
CREATE DATABASE [LibrosWeb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibrosWeb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LibrosWeb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LibrosWeb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\LibrosWeb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibrosWeb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibrosWeb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibrosWeb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibrosWeb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibrosWeb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibrosWeb] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibrosWeb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibrosWeb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibrosWeb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibrosWeb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibrosWeb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibrosWeb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibrosWeb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibrosWeb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibrosWeb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibrosWeb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibrosWeb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibrosWeb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibrosWeb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibrosWeb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibrosWeb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibrosWeb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibrosWeb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibrosWeb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LibrosWeb] SET  MULTI_USER 
GO

ALTER DATABASE [LibrosWeb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibrosWeb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibrosWeb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibrosWeb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LibrosWeb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LibrosWeb] SET QUERY_STORE = OFF
GO

USE [LibrosWeb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [LibrosWeb] SET  READ_WRITE 
GO


